languageCode = "en-gb"
title = "Git Workflow"
baseURL = "https://swipeandtap.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Git Workdlow** at Swipe & Tap."