languageCode = "en-gb"
title = "Git Workflow"
baseURL = "https://github.com/SwipeAndTap/cupper"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Git Workdlow** at Swipe & Tap."